### PR TITLE
[Misc] Fix implicit precision loss warnings

### PR DESCRIPTION
**Pull request by rsanchezsaez**
Fixes a few implicit precision loss warnings when compiling for 64-bit architectures.

### CODE REVIEW

**Comment by rsanchezsaez** [comment]
@sweeneychris: Friendly ping.  ;-)

**Comment by sweeneychris** [comment]
@rsanchezsaez I have been trying to merge this pull request into Theia, but Gerrit (which I use to do code reviews) is not letting me grab the pull request for some reason. It keeps saying "failed" when I try to import it. I'll keep trying every few days in hopes that it works!

**Comment by rsanchezsaez** [comment]
Thanks! Let me know if there's anything I can do to help.

**Comment by sweeneychris** [comment]
I've tried a few more times and Gerrit seems to not like this PR.

One thing you can do, if it's not too much effort, is to upload the patch through Gerrit directly as outlined here: http://theia-sfm.org/contributions.html#developing-for-theia

Sorry for the delay on this... not sure why the patch isn't importing to Gerrit correctly!

**Comment by rsanchezsaez** [comment]
@sweeneychris Done! https://review.gerrithub.io/#/c/358240/

**Comment by sweeneychris** [comment]
Closing this since we merged through Gerrit. Thanks!

**Pull request closed without merging**
