### PR TITLE
Fix build with latest OpenImageIO

### PR DESCRIPTION
**Pull request by KindDragon**

### CODE REVIEW

**Comment by sweeneychris** [comment]
Is this change backwards compatible? Doesn't seem that way.

I think the better way to do this is to detect the version of OpenImageIO and if it is an old one, you specify the macro #define OIIO_NAMESPACE OpenImageIO

**Comment by KindDragon** [comment]
I don't have old oiio. What version do you use?

**Comment by KindDragon** [comment]
1.7.17?

**Comment by KindDragon** [comment]
@sweeneychris Just try with your OIIO version, maybe it already supports `OIIO_NAMESPACE`

**Comment by KindDragon** [comment]
Fixed in 14421f7

**Pull request closed without merging**
